### ISSUE TITLE
Is it possible to show HTML

### ISSUE THREAD

**Issue by FrDH** [piotrzdziarski/fslightbox#72]
Is it possible to show HTML in the popup?
Something like this now gives a "invalid file" message:

````html
<a href="#my-popup">Open popup</a>
<div class="hidden">
   <div id="my-popup">
      Hello world.
   </div>
</div>
````

**Comment by piotrzdziarski** [comment]
Unfortunately not, lightbox supports only images, HTML5 and YouTube videos, but I will consider adding that feature.

**Comment by s22-tech** [comment]
Has this feature been added yet?  I tried it myself but got an "Invalid source" message.

**Comment by piotrzdziarski** [comment]
@s22-tech Maybe you didn't add the "#" prefix to the ID in the "href" attribute?
```html
<a data-fslightbox=gallery href="#custom-source">
```
Custom sources are supported since a few years: https://fslightbox.com/javascript/documentation/sources#custom-sources
